title: Phuket Wedding & Event Planning Services
url: https://weddingservicephuket.com
baseurl: ""
google_analytics_key: "UA-87739794-16" 
google_maps_javascript_api_key: "AIzaSyCGeJhtwVTR5ZBT6uPolvqcWyHQiq0OIjw"
disqus_shortname: "wedding-services-phuket"

# Default description in social shares for the jekyll-seo-tag gem
description: Wedding Service Phuket is Unique as we provide all the Wedding Services you will ever need for your Wedding or event in Phuket.

# Author details for the jekyll-seo-tag gem
author:
  name: "PC Consulting Asia"
  email: "services@uniquephuket.com"
  twitter: "wedding_phuket"

# Social details for the jekyll-seo-tag gem
social:
  name: "Wedding Service Phuket"
  links:
    - https://github.com/CloudCannon/urban-jekyll-template
    - https://www.weddingplannersphuket.com/
    - http://www.facebook.com/Wedding-Service-Phuket-112838213443265/
    - http://instagram.com/weddingservicesphuket
    - http://www.pinterest.com/UniquePhuket
    - http://www.youtube.com/channel/UCv0Q4oKmrOyuwT3jpaKkWOw

timezone: Etc/UTC

collections:
  staff_members:
    output: false
  clients:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"


exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
